---
abstract: 'Just testing away...'
author:
  - 'Mary Ehlers <ehlers@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  blib: '1.01'
  perl: v5.10.0
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150001'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Testy
no_index:
  directory:
    - t
    - xt
provides:
  Testy:
    file: lib/Testy.pm
    version: '0.001'
requires:
  Path::Tiny: '0'
  perl: v5.10.0
  warnings: '0'
resources:
  bugtracker: https://github.com/regina-verbae/Testy/issues
  repository: git://github.com/regina-verbae/Testy.git
version: '0.001'
x_authority: cpan:EHLERS
x_serialization_backend: 'YAML::Tiny version 1.69'
